[WIP] Cleanup of control code
opentk/GLWpfControl pull request #86
Opened 2022-07-21 23:47 UTC by NogginBops

The goal of this PR is to remove some layers of complexity from the control by both removing some of the bad abstractions introduced as well as introduce diligent error checking which will aid immensely with further development of the control.

2023-02-17 13:19 UTC, varon requested changes
These are generally solid changes. Feel free to ignore anything marked Nitpick based on your judgement.

Much of this comes down to personal style, but I do strongly feel that the `DxGLFramebuffer` helped clarity of the code by keeping the single responsibility principle.

This was clearly separated from the Renderer, which operates *on* the Framebuffer.

Generally I try to design around deeper object composition hierarchies rather than larger objects as it helps keep the level of discoverability very high.

If we do end up keeping the DxGLFramebuffer class, one improvement that would fit well in this theme would be to not execute the GL and DX logic in the constructor - I really didn't like that, and it should likely have been in a static factory method instead.

Thanks again for doing this - I hope the review comments are helpful.

2023-02-17 13:19 UTC, varon commented on src/Example/Example.csproj
> +        <TargetFramework>netcoreapp5.0-windows</TargetFramework>
Do we not want to just jump to like 6 or 7 instead?

2023-02-17 13:19 UTC, varon commented on src/GLWpfControl/DXGLContext.cs
> +        public DxGlContext(GLWpfControlSettings settings) {
Why did we remove the annotation here? - If we are doing that, can we be explicit about nullability analysis in the project settings?

2023-02-17 13:19 UTC, varon commented on src/GLWpfControl/DXGLContext.cs
> +                    out var dxDeviceHandle));
Nitpick: Can we assign that to a local variable? this would help improve clarity on the error checking as being a specific step.

2023-02-17 13:19 UTC, varon commented on src/GLWpfControl/DXGLContext.cs
> +            // shared context available but it's been deleted when we get here.
Ouch. 

Nitpick: Can we explain what triggers that race condition so someone can come and fix it later?

2023-02-17 13:19 UTC, varon commented on src/GLWpfControl/GLWpfControl.cs
> -        }
This function really helped to clarify what was going on here. I would suggest keeping it rather than inlining it.

2023-02-17 13:19 UTC, varon commented on src/GLWpfControl/GLWpfControlSettings.cs
> +    public sealed class GLWpfControlSettings : ICloneable {
Microsoft suggests that we do not implement this interface:
>Because callers of [Clone()](https://learn.microsoft.com/en-us/dotnet/api/system.icloneable.clone?view=net-7.0#system-icloneable-clone) cannot depend on the method performing a predictable cloning operation, we recommend that [ICloneable](https://learn.microsoft.com/en-us/dotnet/api/system.icloneable?view=net-7.0) not be implemented in public APIs.

Sourced from:
https://learn.microsoft.com/en-us/dotnet/api/system.icloneable?view=net-7.0#notes-to-implementers

See also: https://stackoverflow.com/questions/699210/why-should-i-implement-icloneable-in-c

2023-02-17 13:19 UTC, varon commented on src/GLWpfControl/GLWpfControl.cs
> +            _settings = (GLWpfControlSettings)settings.Clone();
See note on `ICloneable` below.

2023-02-17 20:09 UTC, NogginBops commented on src/Example/Example.csproj
> +        <TargetFramework>netcoreapp5.0-windows</TargetFramework>
6 is LTS, so probably that one.

2023-02-17 20:14 UTC, NogginBops commented on src/GLWpfControl/DXGLContext.cs
> +        public DxGlContext(GLWpfControlSettings settings) {
Will add nullable to the csproj!

2023-02-17 20:14 UTC, NogginBops commented on src/GLWpfControl/DXGLContext.cs
> +                    out var dxDeviceHandle));
The return value of `DXInterop.CreateDeviceEx`? Sure.

2023-02-17 20:18 UTC, NogginBops commented on src/GLWpfControl/GLWpfControl.cs
> -        }
I think this was part of the cleanup where I inlined a lot of the functions to see where the abstractions where bad.
The name of the function is pretty bad, and there is a lot of magic going on inside. I think there is something to be done about this code but I don't think keeping this exact function is the way forward.

2023-02-17 20:20 UTC, NogginBops commented on src/GLWpfControl/GLWpfControlSettings.cs
> +    public sealed class GLWpfControlSettings : ICloneable {
Ok fair. I guess we should just not implement the interface and instead just create a `Clone`/`Copy` function that uses `MemberwiseClone()`. The issue that prompted this change was that some properties that where added to the settings where not getting copied, likely because the implementer didn't know they needed to modify the `Copy` function.

2023-03-13 13:01 UTC, NogginBops commented on src/GLWpfControl/DXGLContext.cs
> +                    out var dxDeviceHandle));
This is fixed. I changed things in the COM interop code to make the interop more robust.

2023-03-13 13:01 UTC, NogginBops commented on src/GLWpfControl/GLWpfControlSettings.cs
> +    public sealed class GLWpfControlSettings : ICloneable {
This is fixed now. I just do a shallow clone of the object.

2024-05-30 17:35 UTC, NogginBops commented on src/GLWpfControl/DXGLContext.cs
> +            // shared context available but it's been deleted when we get here.
Made every control have it's own OpenGl context so there is no longer any problems with this.

2024-05-30 17:49 UTC, NogginBops commented
I think I'm done with this PR for 4.3.0. Will look at fixing #109 and #30 for `4.3.1` or `4.4.0`.

2024-05-30 17:54 UTC, merged